### ISSUE TITLE
Report page layout improvements

### ISSUE THREAD

**Issue by TheMapSmith** [VTrans-Rail/crossing-inspection#100]
- [x] Page width
- [x] General organization
- [x] Including actual photos

**Comment by TheMapSmith** [comment]
2/3 done by beta 2. rescheduled for beta 3

**Comment by TheMapSmith** [comment]
Merging all report issues here:
- [x] Surface condition box change color based on condition #70 
- [ ] Add section jumps #89 
- [x] Back button closes tab #142 
- [ ] Y/N check boxes for boolean attributes #86 
- [x] review report page content #87

**Comment by TheMapSmith** [comment]
Notes from #87:
- [x] Handle _null_ fields
- [x] Move "Paved" to "Safety Information" section
- [x] Remove "Signs or Signals" field
- [x] Remove "Dynamic Envelope" field
- [x] Remove "Wayside Horn" field
- [x] Remove "Special Gates" field
- [x] Remove Traffic Signal Control', 'Traffic Pre-Signals', 'Storage Distance', and 'Stop-line Distance'
- [x] Add 'RDS_FUNCL' or Functional Classification
- [x] Add 'RDS_AOTCLASS' or AOT Classification
- [x] Add 'IntRd500' or Intersection Road Within 500' of Crossing
- [x] Add 'IntRdDist' Distance to Intersection if 'IntRd500' = Yes
- [x] Add 'PaveMarkCond' or Pavement Marking Condition
- [x] Add 'Num_Tracks' or Number of Railroad Tracks
